//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckMiddelIncome
    {
        public string row_num { get; set; }
        public long ID { get; set; }
        public string OPENEDUSERNAME { get; set; }
        public string PRIMARY_INVESTOR_FULL_NAME { get; set; }
        public string PRIMARY_INVESTOR_SSN { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public string SPOUSE_SSN { get; set; }
        public Nullable<long> ADVID { get; set; }
        public Nullable<int> ADVFLAG { get; set; }
        public string NAME_AR { get; set; }
        public string STEPNAME { get; set; }
        public string LenderNAME { get; set; }
        public Nullable<long> PROCESS_STEP_ID { get; set; }
        public string PROCESS_NAME { get; set; }
        public string LENDER_USERNAME { get; set; }
        public string WithdrawlSSN { get; set; }
        public Nullable<long> ADVERTISEMENT_CODE { get; set; }
        public Nullable<int> WITHDRAWL_TYPE { get; set; }
        public string ADV_NAME { get; set; }
    }
}
