//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWADVERTISMENT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NEWADVERTISMENT()
        {
            this.CitiesLocations = new HashSet<CitiesLocation>();
        }
    
        public int ID { get; set; }
        public string ADVNAME_AR { get; set; }
        public Nullable<System.DateTime> ADV_STARTDATE { get; set; }
        public Nullable<System.DateTime> ADV_ENDDATE { get; set; }
        public string ADV_IMG { get; set; }
        public string ADV_DESC { get; set; }
        public Nullable<int> PORTALADVID { get; set; }
        public Nullable<System.DateTime> RESERVATIONSTARTDATE { get; set; }
        public Nullable<System.DateTime> RESERVATIONSENDDATE { get; set; }
        public Nullable<decimal> DOWNPAYMENT_AMOUNT { get; set; }
        public string BOURCHOUR { get; set; }
        public Nullable<System.DateTime> REGISTRATIONSTARTDATE { get; set; }
        public Nullable<System.DateTime> REGISTRATIONSENDDATE { get; set; }
        public Nullable<bool> ISCLOSED { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitiesLocation> CitiesLocations { get; set; }
    }
}
