//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class NewPortalDBEntities : DbContext
    {
        public NewPortalDBEntities()
            : base("name=NewPortalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<v_Martial_Status> v_Martial_Status { get; set; }
        public virtual DbSet<v_CLASSIFICATION_OF_WORK> v_CLASSIFICATION_OF_WORK { get; set; }
        public virtual DbSet<v_GOVERNRATE> v_GOVERNRATE { get; set; }
        public virtual DbSet<v_ACADEMIC_DEGREE> v_ACADEMIC_DEGREE { get; set; }
        public virtual DbSet<v_RESIDENCE_TYPE> v_RESIDENCE_TYPE { get; set; }
        public virtual DbSet<v_ADVERTISMENT> v_ADVERTISMENT { get; set; }
        public virtual DbSet<HDB_Payment_Confirmation> HDB_Payment_Confirmation { get; set; }
        public virtual DbSet<RegisterSSN> RegisterSSNs { get; set; }
        public virtual DbSet<NEWADVERTISMENT> NEWADVERTISMENTS { get; set; }
        public virtual DbSet<TotalPaymentForClient> TotalPaymentForClients { get; set; }
        public virtual DbSet<V_Dim_subsidy> V_Dim_subsidy { get; set; }
        public virtual DbSet<V_Transaction_Transformation> V_Transaction_Transformation { get; set; }
        public virtual DbSet<TempUnitReserverf> TempUnitReserverfs { get; set; }
        public virtual DbSet<UBSIDY_REQUESTED_UNIT> UBSIDY_REQUESTED_UNIT { get; set; }
        public virtual DbSet<SSNTRIESNOACCEPTE> SSNTRIESNOACCEPTEs { get; set; }
        public virtual DbSet<subsidy_request> subsidy_request { get; set; }
        public virtual DbSet<EXCEPTIONSSN> EXCEPTIONSSNs { get; set; }
        public virtual DbSet<v_PROJECTS> v_PROJECTS { get; set; }
        public virtual DbSet<SETTING> SETTINGS { get; set; }
        public virtual DbSet<Unconditional_Unit> Unconditional_Unit { get; set; }
        public virtual DbSet<SSNPreviousTaken> SSNPreviousTakens { get; set; }
        public virtual DbSet<ReservSSN> ReservSSNs { get; set; }
        public virtual DbSet<Portal_Logger> Portal_Logger { get; set; }
        public virtual DbSet<CheckMiddelIncome> CheckMiddelIncomes { get; set; }
        public virtual DbSet<EXCEPTION_SSN_RESERV> EXCEPTION_SSN_RESERV { get; set; }
        public virtual DbSet<EXCEPTION_HAVE_APP> EXCEPTION_HAVE_APP { get; set; }
        public virtual DbSet<v_Unconditional_Unit> v_Unconditional_Unit { get; set; }
        public virtual DbSet<SSN_CAN_REG> SSN_CAN_REG { get; set; }
        public virtual DbSet<TamwelType> TamwelTypes { get; set; }
        public virtual DbSet<Subsidy_Unit_Wish> Subsidy_Unit_Wish { get; set; }
        public virtual DbSet<SubsidyWhish> SubsidyWhishes { get; set; }
        public virtual DbSet<CitiesLocation> CitiesLocations { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<Allsubsidy_requests> Allsubsidy_requests { get; set; }
        public virtual DbSet<Requested_Unit> Requested_Unit { get; set; }
    
        public virtual ObjectResult<Nullable<long>> Get_Subsidy_RequestID(string ssn)
        {
            var ssnParameter = ssn != null ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<long>>("Get_Subsidy_RequestID", ssnParameter);
        }
    
        public virtual int CheckReservedForsameUser(string ssn, Nullable<long> unitid)
        {
            var ssnParameter = ssn != null ?
                new ObjectParameter("ssn", ssn) :
                new ObjectParameter("ssn", typeof(string));
    
            var unitidParameter = unitid.HasValue ?
                new ObjectParameter("unitid", unitid) :
                new ObjectParameter("unitid", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CheckReservedForsameUser", ssnParameter, unitidParameter);
        }
    
        public virtual ObjectResult<GETCustomersUnits_Result> GETCustomersUnits(string sSN)
        {
            var sSNParameter = sSN != null ?
                new ObjectParameter("SSN", sSN) :
                new ObjectParameter("SSN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GETCustomersUnits_Result>("GETCustomersUnits", sSNParameter);
        }
    }
}
