//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Portal_Logger
    {
        public int ID { get; set; }
        public Nullable<System.Guid> loggerID { get; set; }
        public string USERNAME { get; set; }
        public string IPADDRESS { get; set; }
        public string AREAACCESSED { get; set; }
        public string CONTROLLERNAME { get; set; }
        public string ACTIONAME { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
        public string browser { get; set; }
        public string PARAMETERSFORM { get; set; }
    }
}
