//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RegisterSSN
    {
        public long ID { get; set; }
        public string FullName { get; set; }
        public string SSN { get; set; }
        public string Mobile { get; set; }
        public string Password { get; set; }
        public string VerificationCode { get; set; }
        public Nullable<int> Gander { get; set; }
        public Nullable<int> IsClosed { get; set; }
        public Nullable<bool> Verified { get; set; }
        public byte[] SALT { get; set; }
        public string Token { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> VerifyCount { get; set; }
        public Nullable<System.DateTime> LastPasswordRestore { get; set; }
        public Nullable<int> PasswordRestoreNumber { get; set; }
        public Nullable<System.DateTime> RegisterDate { get; set; }
        public Nullable<System.DateTime> LastloginDate { get; set; }
    }
}
