//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requested_Unit
    {
        public long ID { get; set; }
        public string UNIT_NUMBER { get; set; }
        public string STREET_NAME { get; set; }
        public Nullable<long> LEVEL_NUMBER { get; set; }
        public Nullable<long> NUMBER_OF_LEVELS_IN_BUILDING { get; set; }
        public string BUILDING_NUMBER { get; set; }
        public Nullable<double> AREA { get; set; }
        public string CONTRACTOR_NAME { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<long> UNIT_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public Nullable<long> PROJECT_TYPE_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<long> UNIT_TYPE_ID { get; set; }
        public Nullable<long> LOCATION_TYPE_ID { get; set; }
        public Nullable<long> GOVERNORATE_ID { get; set; }
        public Nullable<long> FINISH_LEVEL_ID { get; set; }
        public Nullable<double> SELLING_PRICE { get; set; }
        public Nullable<long> SUBSIDY_REQUEST_ID { get; set; }
        public Nullable<short> IS_NEW_COMMUNITY { get; set; }
        public string LEVEL_IN_BUILDING { get; set; }
        public Nullable<int> ADVERTISMENT_ID { get; set; }
        public string UnitCode { get; set; }
    }
}
