//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SSNTRIESNOACCEPTE
    {
        public int ID { get; set; }
        public string SSN { get; set; }
        public Nullable<int> NoOfTries { get; set; }
        public string SPOUSE_SSN { get; set; }
        public Nullable<int> SSNORSPOUSE { get; set; }
        public Nullable<int> HAVEBEFORE { get; set; }
        public Nullable<int> INADVONLY { get; set; }
        public Nullable<int> STATUSCODE { get; set; }
        public string RESULT { get; set; }
    }
}
