//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subsidy_Unit_Wish
    {
        public int ID { get; set; }
        public string SSN { get; set; }
        public Nullable<long> Subsidy_Request_Id { get; set; }
        public string Unit_Code { get; set; }
        public Nullable<int> Unit_ID { get; set; }
        public Nullable<System.DateTime> Create_Date { get; set; }
        public Nullable<bool> F_Deleted { get; set; }
    }
}
