//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TempUnitReserverf
    {
        public long ID { get; set; }
        public Nullable<long> RequestedUnitID { get; set; }
        public string SSN { get; set; }
        public Nullable<long> SUbsidrRequestID { get; set; }
        public Nullable<int> IstempOrReserved { get; set; }
        public Nullable<System.DateTime> CancelationReservedDate { get; set; }
        public string UNITCODE { get; set; }
        public Nullable<long> PROJECTID { get; set; }
        public Nullable<int> IS_CANCELED { get; set; }
        public Nullable<System.DateTime> Reservedate { get; set; }
    }
}
