//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TotalPaymentForClient
    {
        public string row_num { get; set; }
        public Nullable<double> TotalDOwnPAyment { get; set; }
        public string CLIENT_SSN { get; set; }
        public Nullable<long> ADVERTISEMENT_CODE { get; set; }
    }
}
