//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Dim_subsidy
    {
        public string Marial_Name { get; set; }
        public string Gov_Name { get; set; }
        public string CityName { get; set; }
        public string Lender_Name { get; set; }
        public string Project_type_Name { get; set; }
        public string Project_Name { get; set; }
        public string PRIMARY_INVESTOR_SSN { get; set; }
        public Nullable<double> DOWNPAYMENT_SUBSIDY { get; set; }
        public Nullable<double> INSTALMENT_SUBSIDY { get; set; }
        public Nullable<double> TOTAL_APPROVED_SUBSIDY_AMOUNT { get; set; }
        public Nullable<double> LOAN_TERMS_LOAN_AMOUNT { get; set; }
        public string PRIMARY_INVESTOR_FULL_NAME { get; set; }
        public Nullable<double> PRIMARY_INVESTOR_MONTHLY_INCOME { get; set; }
        public string PRIMARY_INVESTOR_GENDER { get; set; }
        public string SPOUSE_FULL_NAME { get; set; }
        public string SPOUSE_SSN { get; set; }
        public Nullable<System.DateTime> LOAN_TERMS_CONTRACT_DATE { get; set; }
        public string Adv_Name { get; set; }
        public Nullable<System.DateTime> RECEIPT_ATTACHMENT_DATE { get; set; }
        public Nullable<System.DateTime> DOWN_PAYMENT_CHEQUE_DATE { get; set; }
        public string DOWN_PAYMENT_CHEQUE_NUMBER { get; set; }
        public Nullable<double> DOWN_PAYMENT_CHEQUE_AMOUNT { get; set; }
        public string INSTALMENT_CHEQUE_NUMBER { get; set; }
        public Nullable<System.DateTime> INSTALMENT_CHEQUE_DATE { get; set; }
        public Nullable<double> INSTALMENT_CHEQUE_AMOUNT { get; set; }
        public Nullable<System.DateTime> LOAN_GRANTING_DATE { get; set; }
        public string CONTRACTOR_NAME { get; set; }
        public string UNIT_NUMBER { get; set; }
        public string STREET_NAME { get; set; }
        public Nullable<long> LEVEL_NUMBER { get; set; }
        public Nullable<long> NUMBER_OF_LEVELS_IN_BUILDING { get; set; }
        public string BUILDING_NUMBER { get; set; }
        public Nullable<double> AREA { get; set; }
        public string DISTRICT { get; set; }
        public Nullable<long> UNIT_ID { get; set; }
        public Nullable<double> SELLING_PRICE { get; set; }
        public long ID { get; set; }
        public string PRIMARY_INVESTOR_TELEPHONE_NUMBER { get; set; }
        public string PRIMARY_INVESTOR_CELL_NUMBER { get; set; }
        public Nullable<double> PRIMARY_INVESTOR_ANNUAL_INCOME { get; set; }
        public Nullable<System.DateTime> PRIMARY_INVESTOR_BIRTH_DATE { get; set; }
        public Nullable<double> PRIMARY_INVESTOR_TOTAL_MONTHLY_INCOME { get; set; }
        public Nullable<double> PRIMARY_INVESTOR_TOTAL_ANNUAL_INCOME { get; set; }
        public string SPOUSE_TELEPHONE_NUMBER { get; set; }
        public string SPOUSE_CELL_NUMBER { get; set; }
        public string SPOUSE_GENDER { get; set; }
        public Nullable<double> SPOUSE_MONTHLY_INCOME { get; set; }
        public Nullable<double> SPOUSE_ANNUAL_INCOME { get; set; }
        public Nullable<System.DateTime> SPOUSE_BIRTH_DATE { get; set; }
        public Nullable<short> SPOUSE_EGYPTIAN { get; set; }
        public Nullable<double> SPOUSE_TOTAL_MONTHLY_INCOME { get; set; }
        public Nullable<double> SPOUSE_TOTAL_ANNUAL_INCOME { get; set; }
        public Nullable<short> SPOUSE_IS_WORKING { get; set; }
        public string PRIMARY_INVESTOR_EMPLOYER_NAME { get; set; }
        public string PRIMARY_INVESTOR_EMPLOYER_TELEPHONE_NUMBER { get; set; }
        public string PRIMARY_INVESTOR_EMPLOYER_ADDRESS { get; set; }
        public Nullable<long> PRIMARY_INVESTOR_CLASSIFICATION_OF_WORK_ID { get; set; }
        public string PRIMARY_INVESTOR_OTHER_WORK_CLASSIFICATIONS { get; set; }
        public Nullable<long> PRIMARY_INVESTOR_ACADEMIC_DEGREE_ID { get; set; }
        public Nullable<short> PRIMARY_INVESTOR_IS_CAR_OWNER { get; set; }
        public string SPOUSE_EMPLOYER_NAME { get; set; }
        public string SPOUSE_EMPLOYER_TELEPHONE_NUMBER { get; set; }
        public string SPOUSE_OTHER_WORK_CLASSIFICATIONS { get; set; }
        public string SPOUSE_EMPLOYER_ADDRESS { get; set; }
        public Nullable<long> SPOUSE_CLASSIFICATION_OF_WORK_ID { get; set; }
        public Nullable<long> SPOUSE_ACADEMIC_DEGREE_ID { get; set; }
        public Nullable<short> SPOUSE_IS_CAR_OWNER { get; set; }
        public string CURRENT_RESIDENCE_STREET_NAME { get; set; }
        public string CURRENT_RESIDENCE_BUILDING_NUMBER { get; set; }
        public string CURRENT_RESIDENCE_UNIT_NUMBER { get; set; }
        public string CURRENT_RESIDENCE_POSTAL_CODE { get; set; }
        public Nullable<long> CURRENT_RESIDENCE_GOVERNORATE_ID { get; set; }
        public string CURRENT_RESIDENCE_CITY { get; set; }
        public Nullable<long> CURRENT_RESIDENCE_RESIDENCE_TYPE_ID { get; set; }
        public string CURRENT_RESIDENCE_OTHER_RESIDENCE_INFO { get; set; }
        public string CURRENT_RESIDENCE_COMMENT { get; set; }
        public Nullable<long> NUMBER_OF_FAMILY_MEMBERS { get; set; }
        public Nullable<short> IS_JOINT_OWNERSHIP { get; set; }
        public Nullable<long> MARITAL_STATUS_ID { get; set; }
        public Nullable<long> REJECTION_REASON_ID { get; set; }
        public Nullable<double> FAMILY_MONTHLY_INCOME { get; set; }
        public Nullable<long> MASTER_AGREEMENT_ID { get; set; }
        public Nullable<long> FIELD_INVESTIGATION_STATUS_ID { get; set; }
        public Nullable<long> FIELD_INVESTIGATION_REJECTION_REASON_ID { get; set; }
        public string FIELD_INVESTIGATION_REJECTION_DETAILS { get; set; }
        public Nullable<long> MINISTRY_INVESTIGATION_STATUS_ID { get; set; }
        public string MINISTRY_INVESTIGATION_REJECTION_DETAILS { get; set; }
        public Nullable<long> MINISTRY_FINAL_INVESTIGATION_STATUS_ID { get; set; }
        public string MINISTRY_FINAL_INVESTIGATION_REJECTION_DETAILS { get; set; }
        public string STUDY_AND_FOLLOWUP_DECISION { get; set; }
        public string FOLDER_NUMBER { get; set; }
        public Nullable<long> ISCORE_STATUS_ID { get; set; }
        public string ISCORE_REJECTION_REASON { get; set; }
        public Nullable<System.DateTime> UNIT_ASSIGNMENT_COMMITTE_DATE { get; set; }
        public string UNIT_ASSIGNMENT_COMMITTE_NUMBER { get; set; }
        public Nullable<double> UNIT_APPRAISED_VALUE { get; set; }
        public string UNIT_APPRAISER_NUMBER { get; set; }
        public string UNIT_APPRAISER_NAME { get; set; }
        public Nullable<double> LOAN_TERMS_DOWN_PAYMENT { get; set; }
        public Nullable<double> LOAN_TERMS_INTREST_RATE { get; set; }
        public Nullable<double> LOAN_TERMS_LOAN_PERIOD { get; set; }
        public Nullable<double> LOAN_TERMS_ANNUAL_INSTALMENT_INCEASE { get; set; }
        public Nullable<double> LOAN_TERMS_ANNUAL_INSTALMENT_PERIOD { get; set; }
        public Nullable<double> LOAN_TERMS_MONTHLY_INSTALMENT_FOR_FIRST_YEAR { get; set; }
        public string LOAN_TERMS_LOAN_NUMBER_AT_LENDER { get; set; }
        public Nullable<double> LOAN_TERMS_UNIT_PRICE_INCLUDING_LOAN_COST { get; set; }
        public string LOAN_TERMS_PROPERTY_EVALUATOR_NAME { get; set; }
        public string LOAN_TERMS_PROPERTY_EVALUATOR_NUMBER { get; set; }
        public string FINANCIAL_APPROVAL_MEMO_NUMBER { get; set; }
        public string RECEIPT_NUMBER { get; set; }
        public Nullable<System.DateTime> REQUEST_STEP_DATE { get; set; }
        public Nullable<long> SUBSIDY_TERMINATION_STATUS_ID { get; set; }
        public Nullable<long> SUBSIDY_TERMINATION_REASON_ID { get; set; }
        public Nullable<short> IS_ACCEPTED { get; set; }
        public Nullable<short> IS_REJECTED { get; set; }
        public Nullable<short> IS_ACTION_COMPLETE { get; set; }
        public Nullable<long> MINISTR_INVESTIGATION_REJECTION_REASON { get; set; }
        public string INVESTIGATION_COMPANY_USER { get; set; }
        public string RETURN_TO_SCAN_AND_REVIEW_COMMENT { get; set; }
        public string RETURN_TO_INVESTIGATION_COMPANY_COMMENT { get; set; }
        public string SCAN_AND_REVIEW_INVESTIGATION_COMPANY_COMMENT { get; set; }
        public Nullable<long> INVESTIGATION_TYPE { get; set; }
        public Nullable<long> INVESTIGATION_COMPANY { get; set; }
        public Nullable<double> INSTALMENTS_MORTGAGE_YEARS { get; set; }
        public Nullable<double> LOAN_DEDUCTION_RATE { get; set; }
        public Nullable<double> LOAN_NUMBER_OF_PAYMENTS { get; set; }
        public Nullable<double> LOAN_DEDUCTION_PERCENTAGE { get; set; }
        public Nullable<long> MULTIPLE_PAYMENTS_ID { get; set; }
        public Nullable<short> PROCEDURE_NOT_COMPLETE_REASON { get; set; }
        public string PROCEDURE_NOT_COMPLETE_COMMENT { get; set; }
        public Nullable<short> WAITING_LIST_STATUS { get; set; }
        public Nullable<double> OVERALL_LATE_SUBSIDY { get; set; }
        public Nullable<System.DateTime> ORIGINATING_DATE { get; set; }
        public Nullable<double> ESCROW_ACCOUNT { get; set; }
        public Nullable<System.DateTime> SUBSIDY_TERMINATION_DATE { get; set; }
        public Nullable<System.DateTime> INVESTIGATION_SEND_REQUEST_DATE { get; set; }
        public Nullable<System.DateTime> INVESTIGATION_COMPANY_END_REQEUST_DATE { get; set; }
        public Nullable<int> REINVESTIGATION_CREATE_INVOICE { get; set; }
        public Nullable<long> SECOND_REVIEW_DECISION { get; set; }
        public Nullable<System.DateTime> DELETION_DATE { get; set; }
        public Nullable<short> IS_DELETED { get; set; }
        public Nullable<System.DateTime> PAYBACK_DATE { get; set; }
        public Nullable<long> IS_PAYBACK { get; set; }
        public Nullable<long> MINISTRY_FINAL_INVESTIGATION_REJECTION_REASON_ID { get; set; }
        public Nullable<long> MINISTRY_REJECTION_REASON_ID { get; set; }
        public string INSURANCE_NUMBER { get; set; }
        public string FORM_NUMBER { get; set; }
        public Nullable<long> MINISTRY_INVESTIGATION_REJECTION_REASON { get; set; }
        public Nullable<long> SPOUSE_EMPLOYER_GOVERNORATE { get; set; }
        public Nullable<long> PRIMARY_INVESTOR_EMPLOYER_GOVERNORATE { get; set; }
        public Nullable<long> LOAN_TERMS_BULLET_PAYMENT4 { get; set; }
        public Nullable<int> LOAN_TERMS_BULLET_PAYMENT3 { get; set; }
        public Nullable<int> LOAN_TERMS_BULLET_PAYMENT2 { get; set; }
        public Nullable<int> LOAN_TERMS_BULLET_PAYMENT1 { get; set; }
        public Nullable<long> ACTUAL_INVESTIGATION_DATE { get; set; }
        public Nullable<int> IS_REINVESTIGATION_REJECTED { get; set; }
        public Nullable<short> IS_HAVING_WRONG_SUBSIDY_CALCULATION { get; set; }
        public Nullable<long> CSR_PENDING_PROCEDURE_NOT_COMPLETE_REASONS { get; set; }
        public Nullable<long> ISCORE_REJECTION_REASONS { get; set; }
        public string Clasdsification_Of_Work_Name { get; set; }
        public Nullable<long> AgeYears { get; set; }
        public Nullable<int> Adv_ID { get; set; }
        public string Applicant_Type { get; set; }
        public string Company_Name { get; set; }
        public Nullable<double> Investegation_Precentage { get; set; }
        public string Lender_user_Name { get; set; }
        public string request_id { get; set; }
        public Nullable<long> GOVERNORATE_ID { get; set; }
        public Nullable<long> City_ID { get; set; }
        public Nullable<long> Lender_ID { get; set; }
    }
}
