//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Martial_Status
    {
        public string row_num { get; set; }
        public Nullable<long> ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
    }
}
