//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_PROJECTS
    {
        public string row_num { get; set; }
        public Nullable<long> ID { get; set; }
        public string NAME_AR { get; set; }
        public string NAME_EN { get; set; }
        public Nullable<long> PROJECT_TYPE_ID { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public Nullable<double> UNIT_PRICE { get; set; }
        public Nullable<short> IS_ACTIVE { get; set; }
        public string OWNER { get; set; }
        public string DISTRICT { get; set; }
        public string NEIGHBORHOOD { get; set; }
        public string AREAS { get; set; }
        public string LOCATION { get; set; }
        public Nullable<short> IS_BEING_UPDATED { get; set; }
        public string ADDITIONAL_NOTES { get; set; }
        public string SUBSIDY_EXCEL_NAME { get; set; }
        public Nullable<long> MFF_PROJECT_CATEGORIZATION_ID { get; set; }
        public Nullable<long> ADVERTISEMENT_ID { get; set; }
        public Nullable<double> MAX_LOAN_PERIOD { get; set; }
        public Nullable<double> MIN_LOAN_PERIOD { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<long> CITYID { get; set; }
        public Nullable<long> ADVID { get; set; }
    }
}
