//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Transaction_Transformation
    {
        public string row_num { get; set; }
        public Nullable<long> ID { get; set; }
        public Nullable<System.DateTime> PAYMENT_DATE { get; set; }
        public string PAYMENT_NUMBER { get; set; }
        public string SSN { get; set; }
        public Nullable<double> TOTAL_AMOUNT { get; set; }
        public Nullable<short> IS_CANCELLED { get; set; }
        public string TRANSACTION_REF_NUM { get; set; }
        public Nullable<System.DateTime> CREATION_TIMESTAMP { get; set; }
        public string RAW_PAYLOAD { get; set; }
        public Nullable<long> AD_ID { get; set; }
        public Nullable<int> PAYMENT_CHANNEL_ID { get; set; }
        public Nullable<short> IS_VALID { get; set; }
        public Nullable<int> PAYMENT_TYPE { get; set; }
    }
}
