//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShmffPortal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_Unconditional_Unit
    {
        public int ID { get; set; }
        public Nullable<long> GOVERNORATE { get; set; }
        public Nullable<long> CITY { get; set; }
        public string UNIT_CODE { get; set; }
        public string CONTRACTOR { get; set; }
        public string AREA { get; set; }
        public string AREA_CODE { get; set; }
        public string LOCATION { get; set; }
        public string SAMPLE { get; set; }
        public string BUILDING_NUMBER { get; set; }
        public string UNIT_NUMBER { get; set; }
        public string LEVEL_NUMBER { get; set; }
        public string SPACE { get; set; }
        public Nullable<decimal> DISTINCTION_RATIO { get; set; }
        public Nullable<long> ADVERTISEMENT_ID { get; set; }
        public Nullable<long> PROJECT_ID { get; set; }
        public Nullable<System.DateTime> CREATION_DATE { get; set; }
        public Nullable<long> SUBSIDY_REQUEST_ID { get; set; }
        public Nullable<int> UNIT_PRICE { get; set; }
        public Nullable<long> PAYMENT_CONFIRMATION_ID { get; set; }
        public Nullable<short> RESERVED { get; set; }
        public Nullable<int> CONTRACTOR_CODE { get; set; }
        public Nullable<int> MAINTINANCE_DEPOSIT { get; set; }
        public Nullable<int> TOTAL_UNIT_PRICE { get; set; }
        public Nullable<short> IS_CONTRACTED { get; set; }
        public Nullable<double> INSTALLMENT_PRICE { get; set; }
        public Nullable<long> subsidy_requestID { get; set; }
        public string ADV_NAME { get; set; }
        public string PROJECT_NAME { get; set; }
        public string PRIMARY_INVESTOR_SSN { get; set; }
        public Nullable<long> CITY_ID { get; set; }
        public string CITYNAME { get; set; }
        public Nullable<System.DateTime> date_added { get; set; }
        public string PRIMARY_INVESTOR_CELL_NUMBER { get; set; }
    }
}
